"""Stable API / bot contract — do not rename without updating APITELE i18n."""

COUPON_INVALID = "COUPON_INVALID"
COUPON_EXPIRED = "COUPON_EXPIRED"
COUPON_INACTIVE = "COUPON_INACTIVE"
COUPON_NOT_STARTED = "COUPON_NOT_STARTED"
COUPON_WRONG_PRODUCT = "COUPON_WRONG_PRODUCT"
COUPON_WRONG_USER = "COUPON_WRONG_USER"
COUPON_ALREADY_USED_BY_USER = "COUPON_ALREADY_USED_BY_USER"
COUPON_MAX_USES_EXCEEDED = "COUPON_MAX_USES_EXCEEDED"
COUPON_MIN_ORDER_NOT_MET = "COUPON_MIN_ORDER_NOT_MET"
COUPON_MAX_QTY_EXCEEDED = "COUPON_MAX_QTY_EXCEEDED"

ALL_CODES = frozenset(
    {
        COUPON_INVALID,
        COUPON_EXPIRED,
        COUPON_INACTIVE,
        COUPON_NOT_STARTED,
        COUPON_WRONG_PRODUCT,
        COUPON_WRONG_USER,
        COUPON_ALREADY_USED_BY_USER,
        COUPON_MAX_USES_EXCEEDED,
        COUPON_MIN_ORDER_NOT_MET,
        COUPON_MAX_QTY_EXCEEDED,
    }
)
